### ISSUE TITLE
Upstash Ratelimit Error in GH Action

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [upstash/ratelimit#76]
Hi, while running my GH Action I got this error from upstash:

```
Failed to record analytics TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:117***:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HttpClient.request (file:///home/runner/work/Weather-App/Weather-App/node_modules/.pnpm/@upstash+redis@1.22.1/node_modules/@upstash/redis/esm/pkg/http.js:90:23)
    at async HIncrByCommand.exec (file:///home/runner/work/Weather-App/Weather-App/node_modules/.pnpm/@upstash+redis@1.22.1/node_modules/@upstash/redis/esm/pkg/commands/command.js:55:35)
    at async /home/runner/work/Weather-App/Weather-App/node_modules/.pnpm/@upstash+core-analytics@0.0.6/node_modules/@upstash/core-analytics/dist/index.js:125:9
    at async Promise.all (index 0)
    at async Analytics.ingest (/home/runner/work/Weather-App/Weather-App/node_modules/.pnpm/@upstash+core-analytics@0.0.6/node_modules/@upstash/core-analytics/dist/index.js:120:5)
    at async Analytics.record (/home/runner/work/Weather-App/Weather-App/node_modules/.pnpm/@upstash+ratelimit@1.0.0/node_modules/@upstash/ratelimit/dist/index.js:60:5)
    at async Promise.all (index 1) {
  cause: Error: getaddrinfo ENOTFOUND feasible-urchin-36877.upstash.io,
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -***08,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'feasible-urchin-36877.upstash.io,'
  }
}
```

With this Ratelimit code:

```
const ratelimit = new Ratelimit({
  redis,
  limiter: Ratelimit.slidingWindow(
    parseInt(env.UPSTASH_RATELIMITER_TOKENS_PER_TIME),
    UPSTASH_RATELIMITER_TIME_INTERVAL,
  ),
  analytics: true,
  prefix: "@upstash/ratelimit",
});

const rateLimitMiddleware = t.middleware(async ({ ctx, path, next }) => {
  const identifier = `${ctx.ip}:${path}`;
  // log.debug("identifier", { identifier });
  const { success, remaining } = await ratelimit.limit(identifier);
  // log.debug("remaining", { remaining });
  ctx.res.setHeader(
    "X-RateLimit-Limit",
    env.UPSTASH_RATELIMITER_TOKENS_PER_TIME,
  );
  ctx.res.setHeader("X-RateLimit-Remaining", remaining);
  if (!success) {
    log.warn("Rate limit exceeded", { ip: identifier });
    throw new TRPCError({
      code: "INTERNAL_SERVER_ERROR",
      message: "Rate limit exceeded",
    });
  }
  return next();
});
```

**Comment by FleetAdmiralJakob** [comment]
Here is the GH Action: https://github.com/The-Creative-Programming-Group/Weather-App/actions/runs/7420316595/job/20191464495?pr=155

**Comment by fahreddinozcan** [comment]
Hey @FleetAdmiralJakob ,

do you get the same error when you turn off the ratelimit analytics? Can you try it that way so that we can trace the problem

**Comment by FleetAdmiralJakob** [comment]
With analytics false it is not giving an error. But I will turn analytics true because I need the information. So that is not a solution.

**Comment by fahreddinozcan** [comment]
Okey no problem, so we know where the problem most likely occurs rn. We'll investigate this error and respond to you as soon as possible

**Comment by FleetAdmiralJakob** [comment]
Thank you ♥️

**Comment by FleetAdmiralJakob** [comment]
Hi, any updates on this?

**Comment by fahreddinozcan** [comment]
Hey, sorry for the latency. Having a look at it, we've realized that your endpoint contains a comma at the end. 
```
hostname: 'feasible-urchin-36877.upstash.io,'
```
Could you copy the credentials from the Upstash console fresh, and try once again making sure that credentials are correct? This may be the root cause

**Comment by FleetAdmiralJakob** [comment]
Weird, I updated the secrets and now I get this error (different):

![image](https://github.com/upstash/ratelimit/assets/77451351/fa102f5b-0377-4dfa-a246-7d1e624f312d)

https://github.com/The-Creative-Programming-Group/Weather-App/actions/runs/7530871521/job/20498193001

**Comment by FleetAdmiralJakob** [comment]
Ok, I updated the secret and it's still not working (same error). Maybe a GH Action problem, idk.

**Comment by FleetAdmiralJakob** [comment]
I think we have to further investigate this.

**Comment by FleetAdmiralJakob** [comment]
Ok, nvm: I solved the problem by removing the commas at the end of each env: 
![image](https://github.com/upstash/ratelimit/assets/77451351/733875ce-575d-416f-8f3e-ef2e41463db7)
